### ISSUE TITLE
open up the source code!

### ISSUE THREAD

**Issue by guaka** [guaka/couchsurfing#1]
flashback from early 2007

![screen shot 2015-03-12 at 18 54 57](https://cloud.githubusercontent.com/assets/54728/6624532/2e14c9e6-c8ea-11e4-928a-2bdf9c2d1323.png)

**Comment by guaka** [comment]
ping @byu @jxe @caseyfenton

**Comment by simison** [comment]
Brilliant! :-)

![image](https://cloud.githubusercontent.com/assets/87168/6624664/ffce3096-c8a7-11e4-8920-8d57a1f963fe.png)
